AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Redshift adhoc cluster and its resources
Outputs:
  ExportRedshiftClusterRole:
    Export:
      Name: !Sub redshift-adhoc-cluster-role:ExportRedshiftadhocClusterRole
    Value: !GetAtt RedshiftClusterRole.Arn
Parameters:
  WorkgroupNameParameter:
    Type: String
  VpcId:
    Type: String
  SubnetList:
    Description: Comma-separated list of subnet IDs
    Type: String
Resources:
  RedshiftClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: redshift.amazonaws.com
      RoleName: redshift-adhoc-cluster-s3-role
  RedshiftClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the redshift adhoc cluster
      GroupName: redshift-adhoc-cluster-security-group
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: '-1'
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: CIDR range of the default VPC
          FromPort: 5439
          IpProtocol: tcp
          ToPort: 5439
      Tags:
        - Key: Name
          Value: redshift-adhoc-cluster-security-group
  RedshiftClusterWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    DependsOn: RedshiftClusterNamespace
    Properties:
      BaseCapacity: 8
      ConfigParameters:
        - ParameterKey: require_ssl
          ParameterValue: 'true'
      EnhancedVpcRouting: false
      NamespaceName: !Ref RedshiftClusterNamespace
      Port: 5439
      PubliclyAccessible: true
      SecurityGroupIds:
        - !GetAtt RedshiftClusterSecurityGroup.GroupId
      SubnetIds: !Split
        - ','
        - !Ref SubnetList
      WorkgroupName: !Ref WorkgroupNameParameter
  RedshiftClusterNamespace:
    Type: AWS::RedshiftServerless::Namespace
    DependsOn: RedshiftClusterRole
    Properties:
      ManageAdminPassword: true
      DbName: lab
      IamRoles:
        - !GetAtt RedshiftClusterRole.Arn
      NamespaceName: adhoc-cluster
      LogExports:
        - userlog
        - connectionlog
        - useractivitylog
